-- Ручное исправление миграции
-- Выполните эти команды в MySQL клиенте по порядку

-- 1. Проверьте текущий тип колонки
SHOW COLUMNS FROM audit_logs WHERE Field = 'actionType';

-- 2. Если тип ENUM, сначала измените на VARCHAR
ALTER TABLE `audit_logs` MODIFY `actionType` VARCHAR(191) NOT NULL;

-- 3. Проверьте, какие невалидные значения есть
SELECT DISTINCT `actionType`, COUNT(*) as count
FROM `audit_logs`
WHERE `actionType` NOT IN (
  'LOGIN', 'LOGOUT', 'REGISTER', 'SCRIPT_CREATE', 'SCRIPT_DELETE', 'SCRIPT_START',
  'SCRIPT_STOP', 'SCRIPT_RESTART', 'SCRIPT_DEPLOY', 'SCRIPT_EXPIRED', 'SCRIPT_ISSUE',
  'SCRIPT_REVOKE', 'SCRIPT_EXTEND', 'SCRIPT_ACCESS_GRANT', 'SCRIPT_ACCESS_REVOKE',
  'SERVER_ADD', 'SERVER_UPDATE', 'SERVER_DELETE', 'SERVER_TEST_CONNECTION',
  'SERVER_KEY_ADD', 'SERVER_KEY_DELETE', 'SERVER_KEY_UPDATE', 'USER_BLOCK',
  'USER_UNBLOCK', 'USER_ROLE_CHANGE', 'SCRIPT_SETTINGS_UPDATE', 'NEWS_CREATE',
  'NEWS_UPDATE', 'NEWS_DELETE'
)
GROUP BY `actionType`;

-- 4. Обновите все невалидные значения на временное валидное
UPDATE `audit_logs`
SET `actionType` = 'SCRIPT_SETTINGS_UPDATE'
WHERE `actionType` = 'SCHEDULED_TASK_CREATE'
   OR `actionType` = 'SCHEDULED_TASK_UPDATE'
   OR `actionType` = 'SCHEDULED_TASK_DELETE'
   OR `actionType` = 'SCHEDULED_TASK_RUN'
   OR `actionType` NOT IN (
     'LOGIN', 'LOGOUT', 'REGISTER', 'SCRIPT_CREATE', 'SCRIPT_DELETE', 'SCRIPT_START',
     'SCRIPT_STOP', 'SCRIPT_RESTART', 'SCRIPT_DEPLOY', 'SCRIPT_EXPIRED', 'SCRIPT_ISSUE',
     'SCRIPT_REVOKE', 'SCRIPT_EXTEND', 'SCRIPT_ACCESS_GRANT', 'SCRIPT_ACCESS_REVOKE',
     'SERVER_ADD', 'SERVER_UPDATE', 'SERVER_DELETE', 'SERVER_TEST_CONNECTION',
     'SERVER_KEY_ADD', 'SERVER_KEY_DELETE', 'SERVER_KEY_UPDATE', 'USER_BLOCK',
     'USER_UNBLOCK', 'USER_ROLE_CHANGE', 'SCRIPT_SETTINGS_UPDATE', 'NEWS_CREATE',
     'NEWS_UPDATE', 'NEWS_DELETE'
   );

-- 5. Проверьте, что все значения теперь валидны
SELECT DISTINCT `actionType`, COUNT(*) as count
FROM `audit_logs`
WHERE `actionType` NOT IN (
  'LOGIN', 'LOGOUT', 'REGISTER', 'SCRIPT_CREATE', 'SCRIPT_DELETE', 'SCRIPT_START',
  'SCRIPT_STOP', 'SCRIPT_RESTART', 'SCRIPT_DEPLOY', 'SCRIPT_EXPIRED', 'SCRIPT_ISSUE',
  'SCRIPT_REVOKE', 'SCRIPT_EXTEND', 'SCRIPT_ACCESS_GRANT', 'SCRIPT_ACCESS_REVOKE',
  'SERVER_ADD', 'SERVER_UPDATE', 'SERVER_DELETE', 'SERVER_TEST_CONNECTION',
  'SERVER_KEY_ADD', 'SERVER_KEY_DELETE', 'SERVER_KEY_UPDATE', 'USER_BLOCK',
  'USER_UNBLOCK', 'USER_ROLE_CHANGE', 'SCRIPT_SETTINGS_UPDATE', 'NEWS_CREATE',
  'NEWS_UPDATE', 'NEWS_DELETE'
)
GROUP BY `actionType`;
-- Должно вернуть 0 строк

-- 6. Теперь можно безопасно изменить обратно на ENUM с новыми значениями
ALTER TABLE `audit_logs` MODIFY `actionType` ENUM('LOGIN', 'LOGOUT', 'REGISTER', 'SCRIPT_CREATE', 'SCRIPT_DELETE', 'SCRIPT_START', 'SCRIPT_STOP', 'SCRIPT_RESTART', 'SCRIPT_DEPLOY', 'SCRIPT_EXPIRED', 'SCRIPT_ISSUE', 'SCRIPT_REVOKE', 'SCRIPT_EXTEND', 'SCRIPT_ACCESS_GRANT', 'SCRIPT_ACCESS_REVOKE', 'SERVER_ADD', 'SERVER_UPDATE', 'SERVER_DELETE', 'SERVER_TEST_CONNECTION', 'SERVER_KEY_ADD', 'SERVER_KEY_DELETE', 'SERVER_KEY_UPDATE', 'USER_BLOCK', 'USER_UNBLOCK', 'USER_ROLE_CHANGE', 'SCRIPT_SETTINGS_UPDATE', 'NEWS_CREATE', 'NEWS_UPDATE', 'NEWS_DELETE', 'SCHEDULED_TASK_CREATE', 'SCHEDULED_TASK_UPDATE', 'SCHEDULED_TASK_DELETE', 'SCHEDULED_TASK_RUN') NOT NULL;

-- 7. Восстановите правильные значения на основе details (опционально)
-- См. шаги 4 в migration.sql для восстановления правильных значений


